version: '2'

services:
    web:
        image: nginx:latest
        container_name: ${NGINX_NAME}
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./app:/var/www
            - ./etc/nginx/:/etc/nginx/conf.d/
        depends_on:
            - php
            - mysql
    php:
        image: overbool/php:7.2-fpm
        container_name: ${PHP_NAME}
        volumes:
            - ./app:/var/www
            - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        links:
            - mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
           - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_NAME}
        restart: always
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        container_name: ${MYSQL_NAME}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
