version: '2'

services:
  memcached:
    image: memcached:${MEMCACHED_VERSION}
    container_name: ${MEMCACHED_NAME}
    ports:
      - ${MEMCACHED_PORT}:11211
  web:
    image: ${NGINX_IMAGE}
    container_name: ${NGINX_NAME}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - wing-rsync:/var/www/html:nocopy
      - ./etc/nginx/:/etc/nginx/conf.d/
    depends_on:
      - php
      - mysql
  php:
    image: ${PHP_IMAGE}
    container_name: ${PHP_NAME}
    volumes:
      - wing-rsync:/var/www/html:nocopy
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - mysql
  phpmyadmin:
    image: ${PMA_IMAGE}
    container_name: ${PMA_NAME}
    ports:
      - "${PMA_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_NAME}
    restart: always
    depends_on:
      - mysql
  mysql:
    image: ${MYSQL_IMAGE}
    container_name: ${MYSQL_NAME}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
volumes:
  wing-rsync:
    external: true
